
# Noticed that each row in lego_brick contained the name of the color in the name of the brick
# Ran the command: SELECT DISTINCT ON (color_id) name, color_id FROM lego_brick ORDER BY color_id, name;
# which I copy-pasted and used Gemini to generate a colors lookup table for me

colors = {
    1: "White",
    2: "Tan",
    3: "Yellow",
    4: "Orange",
    5: "Red",
    6: "Green",
    7: "Blue",
    8: "Brown",
    9: "Light Gray",
    10: "Dark Gray",
    11: "Black",
    12: "Trans-Clear",
    13: "Trans-Brown",
    14: "Trans-Dark Blue",
    15: "Trans-Light Blue",
    16: "Trans-Neon Green",
    17: "Trans-Red",
    18: "Trans-Neon Orange",
    19: "Trans-Yellow",
    20: "Trans-Green",
    21: "Chrome Gold",
    22: "Chrome Silver",
    23: "Pink",
    24: "Purple",
    25: "Salmon",
    26: "Light Salmon",
    27: "Rust",
    28: "Nougat",
    29: "Earth Orange",
    31: "Medium Orange",
    32: "Light Orange",
    33: "Light Yellow",
    34: "Lime",
    35: "Light Lime",
    36: "Bright Green",
    37: "Medium Green",
    38: "Light Green",
    39: "Dark Turquoise",
    40: "Light Turquoise",
    41: "Aqua",
    42: "Medium Blue",
    43: "Violet",
    44: "Light Violet",
    46: "Glow In Dark Opaque",
    47: "Dark Pink",
    48: "Sand Green",
    49: "Very Light Gray",
    50: "Trans-Dark Pink",
    51: "Trans-Purple",
    52: "Chrome Blue",
    54: "Sand Purple",
    55: "Sand Blue",
    56: "Rose Pink",
    57: "Chrome Antique Brass",
    58: "Sand Red",
    59: "Dark Red",
    60: "Milky White",
    62: "Light Blue",
    63: "Dark Blue",
    64: "Chrome Green",
    65: "Metallic Gold",
    66: "Pearl Light Gray",
    67: "Metallic Silver",
    68: "Dark Orange",
    69: "Dark Tan",
    70: "Metallic Green",
    71: "Magenta",
    72: "Maersk Blue",
    73: "Medium Violet",
    74: "Trans-Medium Blue",
    76: "Medium Lime",
    77: "Pearl Dark Gray",
    78: "Pearl Sand Blue",
    80: "Dark Green",
    81: "Flat Dark Gold",
    82: "Chrome Pink",
    83: "Pearl White",
    84: "Copper",
    85: "Dark Bluish Gray",
    86: "Light Bluish Gray",
    87: "Sky Blue",
    88: "Reddish Brown",
    89: "Dark Purple",
    90: "Light Nougat",
    91: "Light Brown",
    93: "Light Purple",
    94: "Medium Dark Pink",
    95: "Flat Silver",
    96: "Very Light Orange",
    97: "Royal Blue (Old Blue-Violet)",
    98: "Trans-Orange",
    99: "Very Light Bluish Gray",
    100: "Glitter Trans-Dark Pink",
    101: "Glitter Trans-Clear",
    102: "Glitter Trans-Purple",
    103: "Bright Light Yellow",
    104: "Bright Pink",
    105: "Bright Light Blue",
    106: "Fabuland Brown",
    107: "Trans-Pink",
    108: "Trans-Bright Green",
    109: "Dark Royal Blue",
    110: "Bright Light Orange",
    111: "Speckle Black-Silver",
    113: "Trans-Aqua",
    114: "Trans-Light Purple",
    115: "Pearl Gold",
    116: "Speckle Black-Copper",
    117: "Speckle DBGray-Silver",
    118: "Glow In Dark Trans",
    119: "Pearl Very Light Gray",
    120: "Dark Brown",
    121: "Trans-Neon Yellow",
    123: "Mx White",
    124: "Mx Light Bluish Gray",
    125: "Mx Light Gray",
    126: "Mx Charcoal Gray",
    127: "Mx Tile Gray",
    128: "Mx Black",
    129: "Mx Red",
    130: "Mx Pink Red",
    131: "Mx Tile Brown",
    132: "Mx Brown",
    133: "Mx Buff",
    134: "Mx Terracotta",
    135: "Mx Orange",
    136: "Mx Light Orange",
    137: "Mx Light Yellow",
    138: "Mx Ochre Yellow",
    139: "Mx Lemon",
    140: "Mx Olive Green",
    141: "Mx Pastel Green",
    142: "Mx Aqua Green",
    143: "Mx Tile Blue",
    144: "Mx Medium Blue",
    145: "Mx Pastel Blue",
    146: "Mx Teal Blue",
    147: "Mx Violet",
    148: "Mx Pink",
    149: "Mx Clear",
    150: "Medium Nougat",
    151: "Speckle Black-Gold",
    152: "Light Aqua",
    153: "Dark Azure",
    154: "Lavender",
    155: "Olive Green",
    156: "Medium Azure",
    157: "Medium Lavender",
    158: "Yellowish Green",
    159: "Glow In Dark White",
    160: "Fabuland Orange",
    161: "Dark Yellow",
    162: "Glitter Trans-Light Blue",
    163: "Glitter Trans-Neon Green",
    164: "Trans-Light Orange",
    165: "Neon Orange",
    166: "Neon Green",
    167: "Reddish Orange",
    169: "Sienna",
    170: "Satin Trans-Yellow",
    171: "Lemon",
    172: "Warm Yellowish Orange",
    173: "Ochre Yellow",
    174: "Blue Violet",
    175: "Warm Pink",
    210: "Mx Foil Dark Gray",
    211: "Mx Foil Light Gray",
    212: "Mx Foil Dark Green",
    213: "Mx Foil Light Green",
    214: "Mx Foil Dark Blue",
    215: "Mx Foil Light Blue",
    216: "Mx Foil Violet",
    217: "Mx Foil Red",
    218: "Mx Foil Yellow",
    219: "Mx Foil Orange",
    220: "Coral",
    221: "Trans-Light Green",
    222: "Glitter Trans-Orange",
    223: "Satin Trans-Light Blue",
    224: "Satin Trans-Dark Pink",
    225: "Dark Nougat",
    226: "Trans-Light Bright Green",
    227: "Clikits Lavender",
    228: "Satin Trans-Clear",
    229: "Satin Trans-Brown",
    230: "Satin Trans-Purple",
    231: "Dark Salmon",
    232: "Satin Trans-Dark Blue",
    233: "Satin Trans-Bright Green",
    234: "Trans-Medium Purple",
    235: "Reddish Gold",
    236: "Neon Yellow",
    237: "Bionicle Copper",
    238: "Bionicle Gold",
    239: "Bionicle Silver",
    240: "Medium Brown",
    241: "Medium Tan",
    242: "Dark Olive Green",
    243: "Pearl Sand Purple",
    244: "Pearl Black",
    245: "Lilac",
    246: "Light Lilac",
    247: "Little Robots Blue",
    248: "Fabuland Lime",
    249: "Reddish Copper",
    250: "Metallic Copper",
    251: "Trans-Black",
    252: "Pearl Red",
    253: "Pearl Green",
    254: "Pearl Blue",
    255: "Pearl Brown"
}
